# 关于 Tensor

## 常见的Tensor

In [4]:
from torch import tensor
# Scalar 通常是个值
x = tensor(42.)
print(x, x.dim(),x.item())
# Vector 向量，表示特征
v = tensor([1.5,-0.5,3.0])
print(v, v.dim(),v.size())
# Matrix 一般计算的都是矩阵 多行
m = tensor([[1,2],[3,4]])
print(m)
print(m.matmul(m)) # 内积
print(m*m) # 乘法


tensor(42.) 0 42.0
tensor([ 1.5000, -0.5000,  3.0000]) 1 torch.Size([3])
tensor([[1, 2],
        [3, 4]])
tensor([[ 7, 10],
        [15, 22]])
tensor([[ 1,  4],
        [ 9, 16]])


## Tensor的数据类型

###  32位浮点型：torch.FloatTensor (Tensor默认的数据类型)

In [ ]:
import torch

In [ ]:
a = torch.Tensor( [[2,3],[4,8],[7,9]], )
print(a)
print('size:', a.size())
print('dtype:', a.dtype)

b=torch.FloatTensor( [[2,3],[4,8],[7,9]] )
print(b)
print('size:', b.size())
print('dtype:', b.dtype)

### 64位浮点型：torch.DoubleTensor

In [ ]:
# b = torch.DoubleTensor( [[2,3],[4,8],[7,9]] )
b = torch.Tensor( [True, True, False])
print(b)
print('size:', b.size(), 'dtype:', b.dtype)
size = b.size()
c = size[0]
print(c)
for i,t in enumerate(b):
    print(i, t )


### 16位整型：torch.ShortTensor

In [ ]:
b=torch.ShortTensor( [[2,3],[4,8],[7,9]] )
print(b)
print('size:', b.size(), 'dtype:', b.dtype)

### 32位整型：torch.IntTensor

In [ ]:
b=torch.IntTensor( [[2,3],[4,8],[7,9]] )
print(b)
print('size:', b.size(), 'dtype:', b.dtype)

### 64位整型：torch.LongTensor

In [ ]:
b=torch.LongTensor( [[2,3],[4,8],[7,9]] )
print(b)
print('size:', b.size(), 'dtype:', b.dtype)

### 布尔类型：torch.BoolTensor

In [ ]:
b = torch.BoolTensor( [True, True, False])
print(b.int())
print(b)
print('size:', b.size(), 'dtype:', b.dtype)

In [ ]:
import numpy as np
n = np.array([])
a = torch.FloatTensor([1,2,3.2])
print(a)
print(a[0].numpy())
c = np.append(b,0)
print(c[0])


##  类型转换

1. 数据类型转换
    * 在Tensor后加 .long(), .int(), .float(), .double()等即可，也可以用.to()函数进行转换，所有的Tensor类型可参考https://pytorch.org/docs/stable/tensors.html
2. 数据存储位置转换
    * CPU张量 ---->  GPU张量，使用data.cuda()
    * GPU张量 ----> CPU张量，使用data.cpu()
3. 与numpy数据类型转换
    * Tensor---->Numpy  使用 data.numpy()，data为Tensor变量
    * Numpy ----> Tensor 使用 torch.from_numpy(data)，data为numpy变量
4. 与Python数据类型转换
    * Tensor ----> 单个Python数据，使用data.item()，data为Tensor变量且只能为包含单个数据
    * Tensor ----> Python list，使用data.tolist()，data为Tensor变量，返回shape相同的可嵌套的list

### 更改Tensor的数据类型

In [ ]:
a=torch.FloatTensor( (3,2) )
print(a)
print('size:', a.size(), 'dtype:', a.dtype)

b= a.int()
print(b)
print('size:', b.size(), 'dtype:', b.dtype)

### Tensor和numpy数组转换

In [ ]:
import numpy as np
a = torch.randn( size=(4,5),dtype=torch.float32 ) # Tensor转numpy
print(a)
print('size:', a.size(), 'dtype:', a.dtype)

b = a.numpy()
print(b)
print('size:', b.shape, 'dtype:', b.dtype)

c = np.random.randn(3,4) # numpy转Tensor
print(c)
print('size:', c.shape, 'dtype:', c.dtype)

d=torch.from_numpy( c )
print(d)
print('size:', d.size(), 'dtype:', d.dtype)


### Tensor和 python数据类型的转换

In [ ]:
a = torch.randn( size=(4,5),dtype=torch.float32 ) # Tensor转numpy
print('size:', a.size(), 'dtype:', a.dtype)
b = a.tolist()
print(b)
print('type:', type(b))

a = torch.randn( size=(4,1),dtype=torch.float32 ) # Tensor转numpy
print(a)
print('size:', a.size(), 'dtype:', a.dtype)
b = a[0].item()
print(b)
print('type:', type(b))

## 快速创建Tensor

### 特殊tensor
* torch.zeros
* torch.ones
* torch.arange 根据start与stop指定的范围以及step设定的步长，生成一个array

In [ ]:
# 1. 全为0 a
t=torch.zeros( size=(4,5),dtype=torch.float32 )
print('全为0 ',t)
print('size:', t.size(), 'dtype:', t.dtype)
print('全为1 ', torch.ones(size=(3,4)))
print('顺序 ', torch.arange(1,11))
print('步长0.1 ', torch.arange(1,2,0.1))
print('步长-0.1 ', torch.arange(1,0, -0.1))

### 生成随机数Tensor的方法
 * torch.rand() 均匀分布, 从区间[0, 1)的均匀分布中抽取的一组随机数
 * torch.randn() 标准正态分布, 从标准正态分布（均值为0，方差为1，即高斯白噪声）中抽取的一组随机数
 * torch.normal(means, std, out=None) → Tensor 离散正态分布,从指定均值means和标准差std的离散正态分布中抽取的一组随机数
 * ttorch.linspace(start, end, steps=100, out=None) → Tensor 线性间距向量, 在区间start和end上均匀间隔的step个点

In [ ]:
t = torch.rand(size=(4,5))
print(t)
print('size:', t.size(), 'dtype:', t.dtype)
t = torch.randn(2, 3)
print(t)

t = torch.normal(mean=torch.full([10],0.), std=torch.arange(1, 0.0,-0.1))
print(t)
t = torch.linspace(3, 10, steps=5)
print(t)

## Tensor的比较
> Tensor本身就可以进行一些比较, 更详细的资料大家可以去阅读官方文档。

* 等于 torch.equal(tensor1, tensor2) → bool
    > 如果两个张量的尺寸和元素都相同，则返回True，否则返回False。
* 大于 torch.gt(input, other, out=None) → Tensor
* 大于等于 torch.ge(input, other, out=None) → Tensor

In [ ]:
print(torch.equal(torch.Tensor([1, 2]), torch.Tensor([1, 2])))
print(torch.gt(torch.Tensor([1, 2]), torch.Tensor([1, 2])))
# print(torch.gt(torch.Tensor([1, 2, 3]), torch.Tensor([1, 2]))) RuntimeError:  size 要一致
print(torch.gt(torch.Tensor([[1, 2], [3, 4]]), torch.Tensor([[1, 1], [4, 4]])))
print(torch.gte(torch.Tensor([1, 2]), torch.Tensor([1, 2])))


### 2.4.3 修改Tensor形状

|函数|描述|
|:----|:----|
| size() | 返回张量的shape属性
| numel(input) | tensor的元素个数
| view(*shape) | 修改张量的shape属性（view返回的对象与源tensor共享内存，修改一个另一个也被修改。reshape生成新张量） View(-1)展平数组
| resize | 类似view，在size超过时，重新分配内存空间
| item | 若tensor为单元素，返回python的标量
| unsqueeze | 指定维度增加一个 1
| squeeze | 指定维度压缩一个 1

【说明】torch.view与torch.reshpae的异同

1. reshape()可以由torch.reshape(),也可由torch.Tensor.reshape()调用。view()只可由torch.Tensor.view()来调用。
2. 对于一个将要被view的Tensor，新的size必须与原来的size与stride兼容。否则，在view之前必须调用contiguous()方法。
3. 同样也是返回与input数据量相同，但形状不同的tensor。若满足view的条件，则不会copy，若不满足，则会copy
4. 如果您只想重塑张量，请使用torch.reshape。 如果您还关注内存使用情况并希望确保两个张量共享相同的数据，请使用torch.view

In [ ]:
import torch

#生成一个形状为2x3的矩阵
x = torch.randn(2, 3)
print(x)
print( x.size())    # torch.Size([2, 3])
print( x.dim() )    # 2
 # 把x变为3x2的矩阵
print(x.view(3,2))
y=x.view(-1)  #把x展平为1维向量
print(y)

z = torch.unsqueeze(y,0) # 添加一个维度
print(z)
print(z.size(), z.numel()) # 查看z的形状 和元素个数

### 2.4.4 索引操作

|函数|描述|
|:----|:----|
| index_select(input,dim,index) | 指定维度上，选择列或行
| nonzero(input) | 获取非0下标
| masked_select(input,mask) | 使用二元值进行选择
| gather(input, dim, index) | 指定维度选择数据，形状和index（LongTensor类型）一致
| scatter_(input,dim,index,src) | gather的反操作，根据指定索引补充数据

In [ ]:
import torch

#设置一个随机种子
torch.manual_seed(100)
#生成一个形状为2x3的矩阵
x = torch.randn(2, 3)
#根据索引获取第1行，所有数据
x[0,:]
#获取最后一列数据
x[:,-1]
#生成是否大于0的Byter张量
mask = x > 0
# 获取大于0的值
t = torch.masked_select(x,mask)
print(t)
# 获取非0下标,即行，列索引
t = torch.nonzero(mask)
print(t)
#获取指定索引对应的值,输出根据以下规则得到
#out[i][j] = input[index[i][j]][j]  # if dim == 0
#out[i][j] = input[i][index[i][j]]  # if dim == 1
index = torch.LongTensor([[0,1,1]])
a = torch.gather(x,0,index)
print(a)
index = torch.LongTensor([[0,1,1],[1,1,1]])
b = torch.gather(x,1,index)
print(b)
# 把a的值返回到一个2x3的0矩阵中
z = torch.zeros(2,3)
z.scatter_(1,index,b)
print(z)

### 2.4.5 广播机制

In [ ]:
import torch
import numpy as np

A = np.arange(0, 40,10).reshape(4, 1)
B = np.arange(0, 3)
#把ndarray转换为Tensor
A1=torch.from_numpy(A)  #形状为4x1
B1=torch.from_numpy(B)  #形状为3
#Tensor自动实现广播
C=A1+B1
#我们可以根据广播机制，手工进行配置
#根据规则1，B1需要向A1看齐，把B变为（1,3）
B2=B1.unsqueeze(0)  #B2的形状为1x3
#使用expand函数重复数组，分别的4x3的矩阵
A2=A1.expand(4,3)
B3=B2.expand(4,3)
#然后进行相加,C1与C结果一致
C1=A2+B3

### 2.4.6 逐元素操作

|函数|描述|
|:----|:----|
| abs / add  | 绝对值、加
| addcdiv(t,v,t1,t2)  | t1与t2的按元素除后，乘v加t
| addcmul(t,v,t1,t2)  | t1与t2的按元素乘后，乘v加t
| ceil / floor  | 向上取整 向下取整
| clamp(t,min,max)  | 张量限制在指定区间
| exp / log / pow  | 指数，对数，幂
| mul / neg   | 逐个元素乘法 / 取反
| sigmoid / tanh / softmax  | 激活函数
| sign / sqrt  | 取符号 / 开根号



In [ ]:
import torch

t = torch.randn(1, 3)
t1 = torch.randn(3, 1)
t2 = torch.randn(1, 3)
#t+0.1*(t1/t2)
torch.addcdiv(t, 0.1, t1, t2)
#计算sigmoid
torch.sigmoid(t)
#将t限制在[0,1]之间
torch.clamp(t,0,1)
#t+2进行就地运算
t.add_(2)

### 2.4.7 归并操作
归并就是对输入进行归并或合计等操作

这类操作的输入输出形状一般不相同，而且往往是输入大于输出形状。归并操作可以对整个tensor，也可以沿着某个维度进行归并。

|函数|描述|
|:----|:----|
| cumprod(t, axis) | 指定维度的t累乘积
| cumsum | 指定维度的t累加
| dist(a,b,p=2)| 返回a，b之间的p阶范数
| mean / median  | 均值，中位数
| std / var | 标准差 / 方差
| norm(t,p=2)  | t的p阶范数
| prod(t) / sum(t)| 所有元素的 积 / 和

> 归并操作一般涉及一个dim参数，指定沿哪个维进行归并。
> 另一个参数是keepdim，说明输出结果中是否保留维度1，缺省情况是False，即不保留。

In [ ]:
import torch

#生成一个含6个数的向量
a=torch.linspace(0,10,6)
#使用view方法，把a变为2x3矩阵
a=a.view((2,3))
#沿y轴方向累加，即dim=0
b=a.sum(dim=0)   #b的形状为[3]
#沿y轴方向累加，即dim=0,并保留含1的维度
b=a.sum(dim=0,keepdim=True) # b的形状为[1,3]

### 2.4.8 比较操作
比较操作一般进行逐元素比较，有些是按指定方向比较。

|函数|描述|
|:----|:----|
| eq | 是否相等，支持广播
| equal | 是否相同的shape和值
| ge /le /gt/lt| 大于等，小于等，大于，小于
| max /min(t,axis) | 最值
| topk(t,k,axis) | 指定axis维上取最高的k个值

In [ ]:
import torch

x=torch.linspace(0,10,6).view(2,3)
#求所有元素的最大值
torch.max(x)   #结果为10
#求y轴方向的最大值
torch.max(x,dim=0)  #结果为[6,8,10]
#求最大的2个元素
torch.topk(x,1,dim=0)  #结果为[6,8,10],对应索引为tensor([[1, 1, 1]

### 2.4.9 矩阵操作

 |函数|描述|
 |:----|:----|
 | dot(t1,t2) | 计算张量的内积，点积
 | mm(mat1,mat2) / bmm(batch1,batch2) | 计算矩阵乘法/含batch的3D矩阵乘法
 | mv(t1,v1) | 计算矩阵与向量乘法
 | t | 转置
 | svd(t) | SVD分解

【说明】
1. torch的dot与Numpy的dot有点不同，torch中dot对两个为1D张量进行点积运算，Numpy中的dot无此限制。
2. mm是对2D的矩阵进行点积，bmm对含batch的3D进行点积运算。
3. 转置运算会导致存储空间不连续，需要调用contiguous方法转为连续。

In [ ]:
import torch

a = torch.tensor([2, 3])
b = torch.tensor([3, 4])
print( torch.dot(a,b)) # 运行结果为18

x = torch.randint(10,(2,3))
y = torch.randint(6,(3,4))
print(x)
print(y)
print(torch.mm(x,y))
x = torch.randint(10,(2,2,3))
y = torch.randint(6,(2,3,4))
print(torch.bmm(x,y))

### 2.4.10 Pytorch与Numpy比较

| 操作类别 |Numpy| PyTorch |
|:----|:----|:----|
| 数据类型 | np.ndarray | torch.Tensor |
| - | np.float32 | torch.float32,torch.float |
| - | np.float64 | torch.float64,torch.double |
| - | np.float64 | torch.float64,torch.double |
| - | np.int64 | torch.int64,torch.long |
| 数据构建 | np.ndarray([1,2,3,4],dytpye=np.float16) | torch.tensor([1,2,3,4],dtype=torch.float16) |
| - | c.copy() | x.clone() |
| - | np.concatenate | torch.cat |
| 线性代数 | np.dot | torch.mm |
| 属性 | x.ndim | x.dim() |
| 属性 | x.size | x.nelement() |
| 形状操作 | x.reshape | x.reshape(),x.view() |
| - | x.flatter | x.view(-1) |
| 类型转换 | np.floor(x) | torch.floor(x), x.floor() |
| 比较 | np.less | x.lt |
| - | np.less_equal, np.greater | x.le, x.gt |
| - | np.greater_equal, np.equal, np.not_equal | x.gt,x.eq,x.ne |
| 随机种子 | np.random.seed | torch.manual_seed |
